name: Build and Test Monte Carlo Pricer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential pybind11-dev python3-pybind11

    - name: Create virtual environment
      run: |
        python -m venv python/venv

    - name: Install build dependencies
      run: |
        source python/venv/bin/activate
        python -m pip install --upgrade pip
        # Install build dependencies from requirements
        pip install -r python/reqs.txt

    - name: Build C++ library and tests
      run: |
        cd analytics
        mkdir -p build && cd build
        cmake .. -DENABLE_TESTING=ON
        cmake --build .

    - name: Run C++ tests
      run: |
        cd analytics/build
        ./test_curve

    - name: Build and install package
      run: |
        cd python
        chmod +x build_and_install.sh
        ./build_and_install.sh OFF

    - name: Run Python tests
      run: |
        source python/venv/bin/activate
        cd python
        PYTHONPATH=. python -m unittest test.cap_price_test -v 